
DATA_FILE_NAME = '../data/Daily shelter occupancy 2020.json'
DATA_ADDRESS = "SHELTER_ADDRESS"
DATA_OCCUPANCIES = "OCCUPANCIES"
DATA_DATES = "OCCUPANCY_DATES"
DATA_CAPACITIES = "CAPACITIES"
DATA_ORGANIZATION_NAME = "ORGANIZATION_NAME"
DATA_SHELTER_NAME = "SHELTER_NAME"
DATA_CITY  = "SHELTER_CITY"
DATA_POSTAL_CODE = "SHELTER_POSTAL_CODE"
DATA_FACILITY_NAME = "FACILITY_NAME"
DATA_PROGRAM_NAME = "PROGRAM_NAME"
DATA_SECTOR = "SECTOR"


